version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: visor_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./backend
    container_name: visor_backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: visor_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
